// This file was auto-generated by ML.NET Model Builder. 

using System;
using StudentGradePredictorML.Model;

namespace StudentGradePredictorML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Age = 18F,
                Studytime = 2F,
                Failures = 0F,
                Freetime = 3F,
                Absences = 6F,
                G1 = 5F,
                G2 = 6F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual G3 with predicted G3 from sample data...\n\n");
            Console.WriteLine($"Age: {sampleData.Age}");
            Console.WriteLine($"Studytime: {sampleData.Studytime}");
            Console.WriteLine($"Failures: {sampleData.Failures}");
            Console.WriteLine($"Freetime: {sampleData.Freetime}");
            Console.WriteLine($"Absences: {sampleData.Absences}");
            Console.WriteLine($"G1: {sampleData.G1}");
            Console.WriteLine($"G2: {sampleData.G2}");
            Console.WriteLine($"\n\nPredicted G3: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
