// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace StudentGradePredictorML.Model
{
    public class ModelInput
    {
        [ColumnName("school"), LoadColumn(0)]
        public string School { get; set; }


        [ColumnName("sex"), LoadColumn(1)]
        public string Sex { get; set; }


        [ColumnName("age"), LoadColumn(2)]
        public float Age { get; set; }


        [ColumnName("address"), LoadColumn(3)]
        public string Address { get; set; }


        [ColumnName("famsize"), LoadColumn(4)]
        public string Famsize { get; set; }


        [ColumnName("Pstatus"), LoadColumn(5)]
        public string Pstatus { get; set; }


        [ColumnName("Medu"), LoadColumn(6)]
        public float Medu { get; set; }


        [ColumnName("Fedu"), LoadColumn(7)]
        public float Fedu { get; set; }


        [ColumnName("Mjob"), LoadColumn(8)]
        public string Mjob { get; set; }


        [ColumnName("Fjob"), LoadColumn(9)]
        public string Fjob { get; set; }


        [ColumnName("reason"), LoadColumn(10)]
        public string Reason { get; set; }


        [ColumnName("guardian"), LoadColumn(11)]
        public string Guardian { get; set; }


        [ColumnName("traveltime"), LoadColumn(12)]
        public float Traveltime { get; set; }


        [ColumnName("studytime"), LoadColumn(13)]
        public float Studytime { get; set; }


        [ColumnName("failures"), LoadColumn(14)]
        public float Failures { get; set; }


        [ColumnName("schoolsup"), LoadColumn(15)]
        public bool Schoolsup { get; set; }


        [ColumnName("famsup"), LoadColumn(16)]
        public bool Famsup { get; set; }


        [ColumnName("paid"), LoadColumn(17)]
        public bool Paid { get; set; }


        [ColumnName("activities"), LoadColumn(18)]
        public bool Activities { get; set; }


        [ColumnName("nursery"), LoadColumn(19)]
        public bool Nursery { get; set; }


        [ColumnName("higher"), LoadColumn(20)]
        public bool Higher { get; set; }


        [ColumnName("internet"), LoadColumn(21)]
        public bool Internet { get; set; }


        [ColumnName("romantic"), LoadColumn(22)]
        public bool Romantic { get; set; }


        [ColumnName("famrel"), LoadColumn(23)]
        public float Famrel { get; set; }


        [ColumnName("freetime"), LoadColumn(24)]
        public float Freetime { get; set; }


        [ColumnName("goout"), LoadColumn(25)]
        public float Goout { get; set; }


        [ColumnName("Dalc"), LoadColumn(26)]
        public float Dalc { get; set; }


        [ColumnName("Walc"), LoadColumn(27)]
        public float Walc { get; set; }


        [ColumnName("health"), LoadColumn(28)]
        public float Health { get; set; }


        [ColumnName("absences"), LoadColumn(29)]
        public float Absences { get; set; }


        [ColumnName("G1"), LoadColumn(30)]
        public float G1 { get; set; }


        [ColumnName("G2"), LoadColumn(31)]
        public float G2 { get; set; }


        [ColumnName("G3"), LoadColumn(32)]
        public float G3 { get; set; }


    }
}
